apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptydir-simple-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emptydir-simple
  template:
    metadata:
      labels:
        app: emptydir-simple
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "echo 'Hello from emptyDir!' > /data/hello.txt; sleep 3600"]
        volumeMounts:
        - name: emptydir-storage
          mountPath: /data
      volumes:
      - name: emptydir-storage
        emptyDir: {}
