apiVersion: v1
kind: Service
metadata:
  name: bharathi-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: bharathi-app
  ports:
    - port: 80          # The port that will be exposed by the service
      targetPort: 5000  # The port that the container listens on
