apiVersion: v1
kind: Service
metadata:
  name: domain-app1-service
spec:
  type: ClusterIP
  selector:
    app: app1
  ports:
    - port: 80
      targetPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: domain-app2-service
spec:
  type: ClusterIP
  selector:
    app: app2
  ports:
    - port: 80
      targetPort: 8081
