apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bharathi-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: 192.168.99.100.nip.io     # Replace this with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bharathi-clusterip-service
            port:
              number: 80
