apiVersion: v1
kind: Service
metadata:
  name: bharathi-nodeport-service
spec:
  type: NodePort
  selector:
    app: bharathi-app
  ports:
    - port: 80          # The port that will be exposed by the service
      targetPort: 5000  # The port that the container listens on
      nodePort: 30000   # The port on each node that will forward to the service
