apiVersion: v1
kind: Pod
metadata:
  name: hostpath-simple-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo 'Hello from hostPath!' > /mnt/host/hello.txt; sleep 3600"]
    volumeMounts:
    - name: host-storage
      mountPath: /mnt/host
  volumes:
  - name: host-storage
    hostPath:
      path: /tmp/host-data
