apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["config-map-bharathi"]
  verbs: ["get", "list", "watch"]
rules:
- apiGroups: [""]
  resources: ["secret-bharathi"]
  verbs: ["get", "list", "watch"]

